### ISSUE TITLE
no immediate default_value validation

### ISSUE THREAD

**Issue by fwkoch** [ipython/traitlets#263] opened 2016-08-02 16:13 UTC
Regarding validating default values, I'm curious why this is allowed at all:

<img width="512" alt="screen shot 2016-07-29 at 12 44 45 pm" src="https://cloud.githubusercontent.com/assets/9453731/17260011/46ec3af6-558b-11e6-8b69-0792cb7500ef.png">

This seems to go against the emphasis on validating default values in the module description.
> There are also some important difference in our design:
> * enthought.traits does not validate default values.  We do.

I recognize that this default value is validated eventually if the traitlet is part of a HasTraits class; it just happens on instantiation rather than class definition. Of course, dynamic defaults can only be validated at this point, but it seems like static defaults could be validated sooner.

Thanks!

**Comment by rmorshea** [comment] 2016-08-03 00:21
The motivation seems to come from `TraitType._validate(obj, value)` which accepts the current instance.

However in a cursory review, I've realized that vanilla Traitlets only uses this instance for error reporting (for which `this_class` could easily be substituted) or engaging the "cross validation lock" (which seems like a symptom of how `_validate` works, rather than a necessity). While having the instance in `_validate` does have its uses, theses can, and probably should, be fulfilled by cross validators - a `TraitType` ought not know about a `HasTraits` instance to operate.

The only problem: making the necessary changes would cause *huge* breakages.

**Comment by ankostis** [comment] 2016-08-24 03:10
@fwkoch wrote:
> I recognize that this default value is validated eventually if the traitlet is part of a HasTraits class; ...

Actually, it is not always gets validated; for instance, if the default value is invalid, the validation of this class does not raise:

```python
class Foo(HasTraits):
    good = Unicode('BAD')

    @validate('good')
    def _valid_prop(self, proposal):
        if proposal['value'] == 'BAD':
            raise TraitError()
        return proposal['value']

Foo()             ## Not raised!
Foo(good='BAD')   ## Still not raised.
Foo().good='BAD'  ## But this raises OK.
````
To make his validation fire, you need to define the trait with a non-violating value, like this:
```python
class Foo(HasTraits):
    good = Unicode('BAD')

    @validate('good')
    ...

Foo(good='BAD')  ## Screams!
```

Traitlets version: 4.2.2

**Comment by SylvainCorlay** [comment] 2016-08-24 07:32
> The motivation seems to come from TraitType._validate(obj, value) which accepts the current instance. Interestingly I don't think this needs to be the case, because traitlets only appears to use the instance for:

It is needed for the cross validation called from `_validate`.

**Comment by SylvainCorlay** [comment] 2016-08-24 07:37
@ankostis initial values are not cross-validated.

**Comment by SylvainCorlay** [comment] 2016-08-24 07:39
@ankostis I would like to close this. If you wish to enable cross-validation of initial values, can you open a separate issue?

**Comment by ankostis** [comment] 2016-08-24 08:10
The current behavior is not that clear, to open a new bug.
Can we discuss it a bit more here?

I'm not pushing for cross-validation of initial values (you don't mean "default values" here?), or the opposite, for that matter.
But currently the behavior appears not to be consistent, since it depends on specific default-value.
To explain it, I'm re-writting my above example, assuming the same `@validation@ code (not repeated, for brevity), and crafting two classes that have conflicting behavior when invalid constructor-args values are given (are these the "initial-values"?):

```python
>>> class A1(HasTraits):
...    good = Unicode('BAD')
...    ....

>>> class A2(HasTraits):
...    good = Unicode('GOOD')
...    ...

>>> A1('good='BAD')  ## Pass
>>> A2('good='BAD')  ## Scream!
traitlets.traitlets.TraitError
```

So it seems that in A1, the initial-values are not validated, while in A2 they are.
Is this discrepancy by design?

**Comment by SylvainCorlay** [comment] 2016-08-24 08:16
Yes, I meant default values.

**Comment by ankostis** [comment] 2016-08-24 08:21
To continue, the root cause for me it seems to be that default-values get validated against the trait-type, but not against any `@validation@ rules.

**Comment by SylvainCorlay** [comment] 2016-08-24 08:25
Yes, that is right. If you want default values to be cross validated (by cross validated, I mean with the `@validate` decorator), it is not currently the case and it is a valid issue to be raised!

**Comment by ankostis** [comment] 2016-08-24 08:34
You may close this now, thanks for your prompt replies.

**Closed** 2016-08-24 08:41 UTC

**Comment by rmorshea** [comment] 2016-08-24 20:12
@SylvainCorlay, my criticism of `_validate` Isn't that it accepts an instance, but rather that the tasks it performs (static-validation and cross-validation) should actually be done in separate methods. In other words the structure should be:

```python

def _validate(self, inst, value):
    value = _static_validate(value)
    if inst._cross_validation_lock is False:
        value = self._cross_validate(inst, value)
    return value
```

This way `_static_validate` can be invoked at the time the descriptor instance is created.

In this restructure:

1. `TraitType.validate(inst, value)` would actually be called during `_cross_validate` since that's what the signature of the method, which accepts the current instance, implies it should be doing.
2. From what I can tell, all current implementations of `TraitType.validate` in `traitlets` could actually be performed in `_static_validate`. Though doing this in a backward compatible way would require some thought.

**Comment by rmorshea** [comment] 2016-08-24 20:20
I think this issue should be reopened. Given that `HasTraits.add_traits` requires `TraitTypes` to be instantiated outside the context of a class, `Int("1")` should raise to simplify the ensuing traceback (both here, and in general).

**Comment by SylvainCorlay** [comment] 2016-08-24 20:52
Why not. Although not all trait types have a default value, and it is not always initialized at the time when the trait is initialized.

**Comment by rmorshea** [comment] 2016-08-24 20:55
Are you asking why `Int("1")` should raise?

**Comment by rmorshea** [comment] 2016-08-24 20:56
As for `TraitTypes` with `default_value=Undefined`, they wouldn't get validated upon instantiation.

**Comment by rmorshea** [comment] 2016-08-30 19:51
@SylvainCorlay, should this remain closed, or reopened?

I can work on the pr, but it's likely I will forget if it's closed.

**Comment by SylvainCorlay** [comment] 2016-08-30 23:25
@rmorshea I don't think that there is anything to do here.

**Comment by rmorshea** [comment] 2016-08-31 05:13
@SylvainCorlay, so we are allowing `TraitType` instances with bad defaults to go unvalidated until the `instance_init` is called by a `HasTraits` instance? I ask simply because I think static validation at the time `TraitTypes` created is something we could implemented.

**Comment by SylvainCorlay** [comment] 2016-08-31 06:16
I don't see a good reason to use a TraitType instance outside of this
context especially since they cannot be shared accross multiple HasTraits
subclasses.

Besides, default values may be computed dynamically at a later stage, and
the result is stored in a hastraits instance.
