### ISSUE TITLE
Observe Dict change

### ISSUE THREAD

**Issue by fitoprincipe** [ipython/traitlets#495] opened 2018-07-19 20:16 UTC
How to observe when a dict has changes?

``` python
class Foo(HasTraits):
    bar = Dict()

    @observe('bar')
    def _observe_bar(self, change):
        print(change['new'])

foo = Foo()

foo.bar = {}  # prints {}
foo.bar['test'] = 'test'  # does not observe that change
```
I have made a workaround with `copy`, cloning the old value of the dict, setting the new pair, and reassigning `bar` to the clone.. works, but I though it should be easier.

to follow the rules..

> python -c "import IPython; print(IPython.sys_info())"
> {'commit_hash': u'64a584802',
>  'commit_source': 'installation',
>  'default_encoding': 'UTF-8',
>  'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
>  'ipython_version': '5.6.0',
>  'os_name': 'posix',
>  'platform': 'Linux-4.4.0-98-generic-x86_64-with-LinuxMint-18-sarah',
>  'sys_executable': '/usr/bin/python',
>  'sys_platform': 'linux2',
>  'sys_version': '2.7.14 (default, Sep 18 2017, 11:31:52) \n[GCC 5.4.0 20160609]'}

**Comment by rmorshea** [comment] 2018-07-20 13:54
There have actually been a couple of proposals to do this. However it turns out to be a pretty difficult problem to solve. I made the following PR

https://github.com/ipython/traitlets/pull/466

but because of how many downstream projects it might effect, the changes were met with skepticism. I don’t know when I’ll have time to do the work to get it merged.

If you really need this kind of feature then I’d suggest looking at https://github.com/rmorshea/spectate (which I use under the hood in my PR. Otherwise your workaround is your best bet.

**Comment by fitoprincipe** [comment] 2018-07-20 15:44
Impressive PR! I'll stick to my workaround by the moment, but I'd like to see the progress of that PR. Thank you @rmorshea! Great job

**Comment by rmorshea** [comment] 2019-04-04 01:06
Anyone interested in "eventful" traits should check out https://github.com/rmorshea/spectate which was designed to serve this exact purpose. In principle it should be possible to create a `TraitType` the directs events produces by `spectate` to notifications that can be handled by `@observe`

**Closed by rmorshea** 2019-04-04 01:06 UTC
