### ISSUE TITLE
Default values are not cross-validated with `@validation`

### ISSUE THREAD

**Issue by ankostis** [ipython/traitlets#287] opened 2016-08-24 08:33 UTC
While the defaults values are validated against the type of their trait, they are not cross-validated against any `@validate` rules.

This may lead to conflicting behavior in `HasTraits` subclasses when they contain invalid defaults, as exemplified in #263, and copied here for clarity:

``` python
class A1(HasTraits):
   virtue = Unicode('BAD')

   @validate('virtue')
   def _no_evil(self, proposal):
       if proposal['value'] == 'BAD':
           raise TraitError()
       return proposal['value']

class A2(HasTraits):
   virtue = Unicode('GOOD')

   @validate('virtue')
   def _no_evil(self, proposal):
       if proposal['value'] == 'BAD':
           raise TraitError()

>>> A1('virtue='BAD')  ## Pass
>>> A2('virtue='BAD')  ## Screams!
traitlets.traitlets.TraitError
```

**Comment by SylvainCorlay** [comment] 2016-08-24 08:41
Thanks for reposting here. There were some unrelated discussions on the other thread.

**Comment by SylvainCorlay** [comment] 2016-08-30 09:29
I just wanted to point out that it is not a trivial problem and not doing it was a deliberate choice. Basically, it breaks the possibility of a delayed initialization for a value if it is accessed at the cross-validation stage.

**Comment by rmorshea** [comment] 2016-10-21 20:27
I looked into this recently and the problem here is quite subtle:

1. Setting via `A1(virtue='BAD')` invokes a `hold_trait_notifications` context.
2. Cross validation never occurs inside this context `=>` validation of default values cannot occur here.
	+ In other words dynamic defaults created in the context **never** get validated. So even if A1 had a dynamic default of "BAD" via `@default` (which is normally validated) the problem noted above would still persist.
3. The fact that invalid default values are allowed to generate inside `hold_trait_notifications` (dynamic or otherwise) means that they will be used to determine whether change notifications should occur in `TraitType.set`.
	+ This implies that the failure of `A1(virtue=invalid)` to raise is actually an edge case where `invalid` happens to equal `A1.virtue.default_value` and a change notification is never sent to `HasTraits.notify_change`. That failure to notify means that `hold_trait_notifications` never retraces it in the cache of changes.
	+ In short, if we chose `A1(virtue="EVIL")` an error would be raised.

If you take all this together, and we say that validating default isn't something that we will guarantee, then the bug here is actually that `hold_trait_notifications` operates under the assumption that all prior trait values have been validated.

cc: @SylvainCorlay

**Comment by rmorshea** [comment] 2016-10-21 21:08
@minrk fixing the above issues may require some backward incompatible changes!

**Comment by rmorshea** [comment] 2016-11-02 18:55
Some of this issue is addressed by #332, however, the bug in `hold_trait_notifications` still persists.

**Comment by rmorshea** [comment] 2017-06-09 18:08
@ankostis, see https://github.com/jupyter-widgets/ipywidgets/pull/1409 for a reevaluation of traitlets default validation heuristics. If you have any thoughts or opinions, I'd express them there.

**Comment by ankostis** [comment] 2017-06-09 18:59
Indeed, you may close this one to signify the discussion has moved.
Thanks.

**Comment by rmorshea** [comment] 2017-06-10 20:34
@ankostis, even with default cross-validation, you presented an edge case here that is still broken to my knowledge. [This comment](https://github.com/ipython/traitlets/issues/287#issuecomment-255456913) details that problem.

**Comment by rmorshea** [comment] 2017-08-14 22:57
The regression that was caused by cross-validating defaults was deeply problematic. For that reason I am closing this issue.

Given that it is in fact possible to recreate cross validation by accessing the trait during `@default` and calling the requisite methods (*mention me here if those instructions are too vague*). To y knowledge this does not require you to use any private methods of the trait, so while it may look messy, it's also not a hack.

**Closed by rmorshea** 2017-08-14 22:57 UTC
